[package]
name = "graphql"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = {path = "../../"}
wasm-bindgen = "0.2.59"
graphql_client = "0.9.0"
serde = "1.0.105"
itertools = "0.9.0"
