[package]
name = "subscribe"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = {path = "../../"}
wasm-bindgen = "0.2.59"
itertools = "0.8.2"
futures = "0.3.4"
js-sys = "0.3.36"
