[package]
name = "seed"
version = "0.6.0"
description = "A Rust framework for creating web apps, using WebAssembly"
authors = ["DavidOConnor <david.alan.oconnor@gmail.com>"]
license = "MIT"
repository = "https://github.com/seed-rs/seed"
homepage = "https://seed-rs.org"
documentation = "https://docs.rs/seed"
readme = "README.md"
keywords = ["wasm", "webassembly", "frontend", "framework", "web"]
categories = ["wasm", "web-programming"]
edition = "2018"

build = "build.rs"

[build-dependencies]
version_check = "0.9.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.5"

[dependencies]
console_error_panic_hook = "0.1.6"
cookie = { version = "0.12", features = ["percent-encode"] }
enclose = "1.1.6"
gloo-timers = { version = "0.2.0", features = ["futures"] }
indexmap = "1.3.0"
js-sys = "0.3.32"
pulldown-cmark = "0.6.1"
serde = { version = "1.0.103", features = ['derive'] }
serde_json = "1.0.44"
wasm-bindgen = {version = "0.2.59", features = ["serde-serialize"]}
wasm-bindgen-futures = "0.4.9"
# @TODO: remove once we can use entities without `Debug` in `log!` and `error!` on `stable` Rust.
# https://github.com/Centril/rfcs/blob/rfc/quick-debug-macro/text/0000-quick-debug-macro.md#types-which-are-not-debug
dbg = "1.0.4"
futures = "0.3.4"
uuid = { version = "0.8.1", features = ["v4", "wasm-bindgen"] }

[dependencies.web-sys]
version = "0.3.36"
features = [
    "AbortController",
    "AbortSignal",
    "CanvasRenderingContext2d",
    "CustomEvent",
    "CustomEventInit",
    "Document",
    "DomException",
    "Element",
    "Event",
    "EventTarget",
    "HashChangeEvent",
    "Headers",
    "History",
    "HtmlElement",
    "HtmlCanvasElement",
    "HtmlCollection",
    "HtmlDocument",
    "HtmlInputElement",
    "HtmlMenuItemElement",
    "HtmlProgressElement",
    "HtmlOptionElement",
    "HtmlDataElement",
    "HtmlMeterElement",
    "HtmlLiElement",
    "HtmlOutputElement",
    "HtmlParamElement",
    "HtmlTextAreaElement",
    "HtmlSelectElement",
    "HtmlButtonElement",
    "Location",
    "MouseEvent",
    "Node",
    "NodeList",
    "Performance",
    "PointerEvent",
    "PopStateEvent",
    "ReferrerPolicy",
    "Request",
    "RequestCache",
    "RequestCredentials",
    "RequestInit",
    "RequestMode",
    "RequestRedirect",
    "Response",
    "Storage",
    "Text",
    "console",
    "Window",
    "KeyboardEvent",
    "InputEvent",
    "Url",
]

[workspace]
members = [
    "examples/animation_frame",
    "examples/app_builder",
    "examples/counter",
    "examples/counter_advanced",
    "examples/canvas",
    "examples/custom_elements",
    "examples/drop_zone",
    "examples/graphql",
    "examples/markdown",
    "examples/fetch",
    "examples/mathjax",
    "examples/orders",
    # "examples/server_integration",   # has own workspace
    "examples/server_interaction",
    "examples/subscribe",
    "examples/tea_component",
    "examples/todomvc",
    "examples/update_from_js",
    "examples/user_media",
    "examples/websocket",
    "examples/window_events",
]

exclude = [
    # it has own workspace
    "examples/server_integration",
]
