[package]
name = "fetch"
version = "0.1.0"
authors = ["TatriX <tatrics@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = {path = "../../"}
wasm-bindgen = "0.2.55"
serde = { version = "^1.0.103", features = ["derive"] }
futures = "0.3.4"
