name: Main

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        #with:
        #    repository: ButtNaked/delta.git
        #    token: ${{ secrets.EXT_GHA }}

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            profile: minimal

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

        #- name: Run tests
        #  run: cargo make verify_only

      - name: Build
        run: |
          cargo make build_release
          mkdir build
          mv -v index.html public pkg ./build
          ls -a ./build/pkg

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true
