[package]
name = "websocket"
version = "0.1.0"
authors = ["Markus Kohlhase <markus.kohlhase@slowtec.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
# common
serde = { version = "^1.0.103", features = ["derive"] }
serde_json = "^1.0.44"

# server
ws = { version = "0.9.1", optional = true }

#client
seed = { path = "../../", optional = true }
wasm-bindgen = { version = "^0.2.55", optional = true }
js-sys = "0.3.32"
[dependencies.web-sys]
version = "^0.3.32"
features = ["WebSocket", "MessageEvent"]
optional = true

[features]
default = []
client = ["seed", "wasm-bindgen", "web-sys"]
server = ["ws"]

